name: publish
on:
  push:
    tags:
      - v*
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: bigquery-emulator
            asset_name: bigquery-emulator-linux-amd64
          - os: macos-latest
            artifact_name: bigquery-emulator
            asset_name: bigquery-emulator-darwin-amd64
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make emulator/build
      env:
        VERSION: ${{ github.ref }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
